### ISSUE TITLE
Fetching frontend image fails

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#841] opened 2024-03-12 08:33 UTC
For Visual Matching Pairs, the Preload component has a `fetch` call, which, in contrast to the `axios` calls, gives me CORS problems:
<img width="570" alt="Screenshot 2024-03-12 at 09 31 34" src="https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/11174072/7dc6df6a-4245-4334-b1b6-9259ca6162c7">

For now, will introduce a `{mode: 'no-cors'}` workaround, but perhaps there's a less awkward solution.

**Comment by BeritJanssen** [comment] 2024-04-08 09:18
Could this be browser related? I see that Chrome (which I'm using) sets an Authorization header, which other browsers remove. (See table below Fetch API documentation)[https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API]

**Comment by drikusroor** [comment] 2024-04-08 10:42
> Could this be browser related? I see that Chrome (which I'm using) sets an Authorization header, which other browsers remove. [See table below Fetch API documentation](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#browser_compatibility)

Ah good catch, let me test it on Chrome too then 👍

**Comment by drikusroor** [comment] 2024-04-08 13:03
@BeritJanssen I'm experiencing no problems on Chrome either. The only thing that I could think of is this line in `base_settings.py`:

```python
# CORS origin white list from .env
CORS_ORIGIN_WHITELIST = os.getenv(
    "AML_CORS_ORIGIN_WHITELIST",
    "http://localhost:3000,http://127.0.0.1:3000,{}".format(HOMEPAGE)
).split(",")
```

`AML_CORS_ORIGIN_WHITELIST` is not set in my `.env` file. Is it set in yours with a different value perhaps? 🤔

**Comment by drikusroor** [comment] 2024-04-29 08:43
Closed as I could not reproduce it. Let's reopen the issue or create a new one if it pops up again, and then let's try to pin down the reproduction conditions.

**Closed by drikusroor** 2024-04-29 08:43 UTC
Labels: bug
