### ISSUE TITLE
[Congo Matching Pair Quality Control] Rule and feedback provided correctly

### ISSUE THREAD

**Issue by Lia-JX-Li** [Amsterdam-Music-Lab/MUSCLE#985] opened 2024-04-30 19:38 UTC
As a result of the meeting with Henkjan and Ashley on 30.04. We decided that JL will file the most important **three aspects to be tested/quality checked by the MUSCLE team before delivering the product**. I know it could be annoying to check all the details again but we believe more testing is necessary and could discover bugs as early as possible. 
Again, please feel free to close the issue after you have checked it in the code. @Evert-R 

Second aspect:
This aspect is game behavior related. Three things should be checked here: seen/not seen, feedback, score.

The **card's behavior of being seen/not seen** needs to be recorded correctly. Then based on the recorded seen/not seen, the **feedback** and **scoring** should be provided exactly as the following logic:

The feedback and scoring should be only based on whether the second card seen before or not. 
As an example, New = a card hasn't seen before, Old = a card seen before.

NEW OLD - Match - Good job +20 
OLD NEW - Match - Lucky match +10
NEW NEW - Match - Lucky match +10
OLD OLD - Match - Good job +20
NEW OLD - No match - Misremember -10
OLD NEW - No match - No match 0
NEW NEW - No match - No match 0
OLD OLD- No match Misremember -10

**Addtionally,** I have one thing that I would like to get confirmed by the MUSCLE: Now there is no such feature recording how many times a card is seen, but because **every move is recorded with position**, so we could get that information by calculating how many times a particular position is clicked, is that correct?

**Comment by Evert-R** [comment] 2024-05-02 07:29
Problem found: NEW-OLD was set to +10 instead of +20

I managed to recreate the situation by picking the same card as the second one each turn untill I had a match.
So: 2-1, 3-1, 4-1, 5-1 etc..
I have just merged a bugfix for this. So after a git pull this should not happen again.
 
Details:
There was a typo in the original code `turnedCards[1].seen = turnedCards[1].seen = true;`
This was later fixed by assigning `seen` to the `first_card`, but right after clicking on it. I already noticed yesterday that this caused the first_card to be always set to `seen` in the results, which also is a problem.
 
I have now fixed the original typo, so that both cards are set to seen only after logging the results of a turn.
`turnedCards[0].seen = turnedCards[1].seen = true;`

**Comment by Evert-R** [comment] 2024-05-02 14:08
I have confirmed the right behaviour of these situations:

NEW OLD - Match - Good job +20
OLD NEW - Match - Lucky match +10
NEW NEW - Match - Lucky match +10
OLD OLD - Match - Good job +20
NEW OLD - No match - Misremember -10
OLD NEW - No match - No match 0
NEW NEW - No match - No match 0
OLD OLD- No match Misremember -10

**Comment by Evert-R** [comment] 2024-05-02 14:12
**Addtionally, I have one thing that I would like to get confirmed by the MUSCLE: Now there is no such feature recording how many times a card is seen, but because every move is recorded with position, so we could get that information by calculating how many times a particular position is clicked, is that correct?**

Yes that's correct.

**Closed** 2024-05-07 10:14 UTC
